### ISSUE TITLE
Outdated images

### ISSUE THREAD

**Issue by vasiliy-t** [intelsdi-x/snap-docker#30]
Newest images on docker hub updated 3 months ago, any updates planned?

**Comment by IzabellaRaulin** [comment]
hello @vasiliy-t - yes, there is a plan to provide docker image with Snap 1.3. It happens probably within two next weeks, maybe earlier.

**Comment by vasiliy-t** [comment]
Thank you for reply, closing issue, waiting for updated images

**Comment by IzabellaRaulin** [comment]
@vasiliy-t, all images are now up-to-date (including images with Snap in version1.3.0 and the latest one - Snap 2.0.0). See https://hub.docker.com/r/intelsdi/snap/tags/
