### ISSUE TITLE
images assume that containers have internet access

### ISSUE THREAD

**Issue by woodsaj** [intelsdi-x/snap-docker#7]
The images try and pull down the latest snap binaries when the container starts.  If the containers are running inside environments with limited or no internet access, then the containers cant start.

Why cant the Dockerfiles just pull the binaries into the docker image at build time and tag the image with the build version.

**Comment by nanliu** [comment]
We have a few image that has snap version which contains the binary, for example: intelsdi/snap:0.15_xenial.

These prebuilt images don't have an automated update process, so until we have automated docker image build process I think the current binary fetch seems like a good compromise for testing purpose. I'm planning to delete the latest_* tags until we have an automated process in place.

**Comment by woodsaj** [comment]
ok, but if these docker images are only for testing purposes that should be made clear in the description on dockerhub. 

Are there any plans to produce images that users can use in real environments?

**Comment by nanliu** [comment]
We are planning to change the s3 output for snap to match the plugins with arch/os. I will circle back to the docker repo once we resolve this issue:

https://github.com/intelsdi-x/snap/issues/1205

**Comment by nanliu** [comment]
See WIP #10 for goal to split off the docker images. This will take a bit longer, since the change to snap binary output is affecting a bunch of test.

**Comment by nanliu** [comment]
@woodsaj, the new containers ship with binary included. The download behavior is limited to  *_test containers. Please let us know if this addresses your concern.

**Comment by woodsaj** [comment]
yes it does.  Thanks.
